### ISSUE TITLE
Get as a Stream

### ISSUE THREAD

**Issue by klauswuestefeld** [keorn/clj-ipfs-api#1]
This allows for getting huge files:
https://github.com/ipfs/java-ipfs-api/issues/5

**Comment by keorn** [comment]
I moved to clj-http: 15c89e9f48a9333f03b57e409f140bf0f3e7e51c.
Now you can just use whatever options you need for the request. Just do `(ipfs-custom {:as :stream} :swarm :peers)` to get a stream, let me know if you need some parsing for that.

**Comment by keorn** [comment]
Ah, I bumped the version to 1.1 as this changes syntax of `ipfs-custom`, if you want to use it.
